version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
          db:
            condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

  db:
    image: postgres:17
    env_file: .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 2s
      timeout: 2s
      retries: 2
    ports:
      - '5434:5432'
    command: ['postgres', '-c', 'jit=off']

volumes:
  pg-data:

