# Generated by Django 5.2.5 on 2025-08-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Текст вопроса', max_length=255, verbose_name='Вопрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания вопроса', verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(help_text='UUID пользователя', verbose_name='UUID')),
                ('text', models.TextField(help_text='Ответ пользователя на вопрос', verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания ответа пользователя', verbose_name='Время создания')),
                ('question', models.ForeignKey(help_text='Укажите вопрос, к которому относится ответ', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qa_app.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
